export const CONTACT_US = "contact-us";
export const ABOUT_US = "content-pages/view/about-us";
export const NEWS__LATTER = "news-letter";
export const SIGN_UP = "auth/signup";
export const LOGIN = "auth/login";
export const FORGOT_PASSWORD = "auth/forgot";
export const OTP_NEW_PASSWORD = "auth/reset-password";
export const HERO_SECTION = "content-pages/view/hero-section";
export const MEET_DOCTOR = "content-pages/view/meet-doctor";
export const MEDICAL_SERVICES = "content-pages/view/medical-services";
export const SERVICES = "services";
export const SERVICES_ID = `services/view`;
export const FIND_LOCATION = `content-pages/view/find-our-Location`;
export const CATEGORIES = `shop/category`;
export const PRODUCT = `shop/product`;
export const FREE_CONSULTATION = `free-consult`;
export const MEMBER_SHIP = `memberships`;
export const ADD_TO_CART = `cart/create`;
export const ADD_TO_CART_LIST = `cart`;
export const REMOVED_TO_CART = `cart/delete/`;
export const REMOVED_TO_ALL = `cart/delete-all`;
export const CHECK_OUT = `orders/checkout`;
export const BLOGS = `blogs`;
export const BLOG_CONTENT = `content-pages/view/blog`;
export const SERVICE_PROVIDER = `service-provider`;
export const SERVICE_PROVIDER_ID = `service-provider/view/`;
export const SLOTS = `slots/get-slots`;
export const SLOTS_AVAILABLE = `slots/available`;
export const SLOTS_CREATE_CHECK_OUT = `slots/create`;
export const LAST_VISIT = `slots/last-visit`;
export const USER_SUBSCRIPTION_CREATE = `user-subscription/create`;
export const USER_SUBSCRIPTION_BY_ID = `memberships/view/`;
export const USER_SUBSCRIPTION_BY_TOKEN = `user-subscription`;
export const WISHLIST_ADD = `wishlist/create`;
export const CONTACT_US_CONTENT = `content-pages/view/contact-us`;
export const OFFICE_POLICY = `content-pages/view/office-policy`;
export const DISCLAIMER = `content-pages/view/disclaimer`;
export const PRIVACY_POLICY = `pages/view/privacy-and-policy`;
export const PRIVACY_POLICY_CONTENT = `content-pages/view/privacy-policy`;
export const TERM_CONDITION = `pages/view/terms-and-condition`;
export const TERM_CONDITION_CONTENT = `content-pages/view/termservice`;
export const CART_COUNT = `cart/count`;

// PATIENT RESOURCES
export const PATIENT_FORM = `content-pages/view/patient-form`;
export const PATIENT_RESOURCES = `content-pages/view/patient-resources`;
export const PATIENT_EDUCATION = `content-pages/view/patient-education`;
export const INSURANCE = `content-pages/view/insurance	`;
export const BILLING = `content-pages/view/billing	`;
export const FAQ = `faqs`;

// Profile/
export const MY_PROFILE = `me`;
export const MY_PROFILE_IMAGE = `me/update-profile-picture`;
export const UPDATE_PROFILE = `me/update-profile`;
export const UPDATE_PASSWORD = `me/change-password`;
export const SLOTS_MY_APPOINTMENTS = `slots/my-appointments`;
export const SLOTS_APPOINTMENT_CANCEL = `slots/cancel-appointment/`;
export const SLOTS_APPOINTMENT_WAITING_LIST = `slots/get-waiting-list`;
export const ORDERS = `orders`;
export const WISHLIST = `wishlist`;
export const WISHLIST_DELETE_BY_ID = `wishlist/delete/`;
export const ALL_WISHLIST_DELETE = `wishlist/delete-all`;
export const PAYMENT_TRANSACTIONS_RECORD = `transaction`;
export const SITE_SETTINGS = `site-setting`;

// Guest
export const GUEST_CART_CREATE = `guest-cart/create`;
export const GUEST_CART_LIST = `guest-cart`;
export const GUEST_CART_REMOVE = `guest-cart/delete`;
export const GUEST_CART_ALL_REMOVE = `guest-cart/delete-all`;
export const GUEST_CHECK_OUT = `guest-checkout`;
export const GUEST_CART_COUNT =`guest-cart/count`
